# Generated by Django 4.0.4 on 2022-05-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allposts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
